
name: test-tfsec-pr-at-push
on:
  push:
jobs:
  push_test:
    name: Run tfsec-push
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
